// <auto-generated />
using CatchLightning.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatchLightning.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20260904185056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AchievementAchievement", b =>
                {
                    b.Property<int>("DependentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("СonditionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DependentsId", "СonditionsId");

                    b.HasIndex("СonditionsId");

                    b.ToTable("AchievementAchievement");
                });

            modelBuilder.Entity("CatchLightning.Core.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateComplited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GoalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdGoal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplited")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GoalId");

                    b.ToTable("Achivments");
                });

            modelBuilder.Entity("CatchLightning.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CatchLightning.Core.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("AchievementAchievement", b =>
                {
                    b.HasOne("CatchLightning.Core.Models.Achievement", null)
                        .WithMany()
                        .HasForeignKey("DependentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatchLightning.Core.Models.Achievement", null)
                        .WithMany()
                        .HasForeignKey("СonditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatchLightning.Core.Models.Achievement", b =>
                {
                    b.HasOne("CatchLightning.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("CatchLightning.Core.Models.Goal", "Goal")
                        .WithMany("Achivments")
                        .HasForeignKey("GoalId");

                    b.Navigation("Category");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("CatchLightning.Core.Models.Goal", b =>
                {
                    b.HasOne("CatchLightning.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CatchLightning.Core.Models.Goal", b =>
                {
                    b.Navigation("Achivments");
                });
#pragma warning restore 612, 618
        }
    }
}
